### PR TITLE
Make the code build with Qt versions lower than 5.10.

### LINKED ISSUE #383: Unable to build Stacer with make in QT for Manjaro KDE
The output of `make -j $(nproc)` is as follows please help me with that I am new to this 

`[  1%] Automatic MOC for target stacer-core
[  1%] Built target stacer-core_autogen
[ 30%] Built target stacer-core
[ 32%] Automatic MOC and UIC for target stacer
[ 32%] Built target stacer_autogen
[ 33%] Building CXX object stacer/CMakeFiles/stacer.dir/Pages/Search/search_page.cpp.o
/home/aj97/Projects/Stacer/stacer/Pages/Search/search_page.cpp: In member function ‘QList<QStandardItem*> SearchPage::createRow(const QString&)’:
/home/aj97/Projects/Stacer/stacer/Pages/Search/search_page.cpp:338:63: error: ‘class QFileInfo’ has no member named ‘metadataChangeTime’
  338 |     QStandardItem *i_lastChange = new QStandardItem(fileInfo->metadataChangeTime().toString(mSearchResultDateFormat));
      |                                                               ^~~~~~~~~~~~~~~~~~
/home/aj97/Projects/Stacer/stacer/Pages/Search/search_page.cpp:339:37: error: ‘class QFileInfo’ has no member named ‘metadataChangeTime’
  339 |     i_lastChange->setData(fileInfo->metadataChangeTime().toString(mSearchResultDateFormat), rowRole);
      |                                     ^~~~~~~~~~~~~~~~~~
/home/aj97/Projects/Stacer/stacer/Pages/Search/search_page.cpp:340:37: error: ‘class QFileInfo’ has no member named ‘metadataChangeTime’
  340 |     i_lastChange->setData(fileInfo->metadataChangeTime().toString(mSearchResultDateFormat), Qt::ToolTipRole);
      |                                     ^~~~~~~~~~~~~~~~~~
make[2]: *** [stacer/CMakeFiles/stacer.dir/build.make:427: stacer/CMakeFiles/stacer.dir/Pages/Search/search_page.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:192: stacer/CMakeFiles/stacer.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
`

### PR DESCRIPTION
**Pull request by mahiuchun**
QFileInfo::metadataChangeTime() was introduced in Qt 5.10. So a #ifdef is
added around metadataChangeTime() usage.

This should fix #383.

### CODE REVIEW

**Comment by theofficialgman** [comment]
yes something like this is needed to build on less that qt 5.10... please consider merging this PR
